DROP TABLE IF EXISTS media_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS invites;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS media_type;
DROP TYPE IF EXISTS user_role;
